tunnel: starspace-server
credentials-file: ~/.cloudflared/09a1ed32-f980-4dc5-8d12-9e5e4abb14c4.json

ingress:
  - hostname: api.tradefy.biz
    service: http://localhost:5173
  - service: http_status:404
